/**
 * Sitemap deploy gate — runs after `vite build`, as the last step of `npm run build`.
 * ────────────────────────────────────────────────────────────────────────────
 * generate-sitemap.mjs is deliberately non-throwing (a data hiccup must never
 * break a deploy). The trade-off is that a *silent* failure — a stale, empty,
 * missing, or malformed sitemap — could ship unnoticed. THIS script is the loud
 * half of that contract: it inspects the sitemap that actually landed in the
 * build output (dist/) and exits non-zero if anything is wrong, failing the
 * build so the problem is seen instead of deployed.
 *
 * It asserts the sitemap:
 *   1. exists in dist/  (proves vite copied public/ → dist/)
 *   2. is well-formed-ish XML with a <urlset> and at least MIN_URLS <loc>s
 *   3. was regenerated THIS build (its "Generated <iso>" stamp is recent) —
 *      this is what stops a stale checked-in file from silently no-op shipping
 *   4. contains no private/admin/auth path (mirrors the exclusion list)
 *   5. every <loc> is an absolute URL on the expected origin
 */

import { readFileSync, existsSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'
import { isExcludedPath } from './generate-sitemap.mjs'

const __dir = dirname(fileURLToPath(import.meta.url))
const DIST_SITEMAP = join(__dir, '../dist/sitemap.xml')
const BASE_URL = (process.env.SITE_URL || 'https://www.ngoaquaterra.com').replace(/\/+$/, '')

const MIN_URLS = 20          // static routes alone clear this; a near-empty file fails
const MAX_AGE_MINUTES = 120  // must have been generated by this build, not committed stale

const fail = msg => { console.error(`\n❌ Sitemap gate FAILED: ${msg}\n`); process.exit(1) }

if (!existsSync(DIST_SITEMAP)) {
  fail(`dist/sitemap.xml is missing. The generator or the public/→dist/ copy did not run.
   Ensure \`npm run build\` runs \`node scripts/generate-sitemap.mjs\` before \`vite build\`.`)
}

const xml = readFileSync(DIST_SITEMAP, 'utf8')

if (!xml.includes('<urlset')) fail('no <urlset> root element — file is not a valid sitemap.')

// The generator preserves an existing sitemap rather than replacing it with a
// much smaller one (a network blip once collapsed 594 URLs to 31). It refreshes
// the build stamp when it does, so the freshness gate below cannot see it - by
// design, because failing here would throw away the content we just protected.
// It now leaves a PRESERVED marker so the condition is at least VISIBLE. Warn,
// never fail: the sitemap is good, it is just older than this build.
const preserved = xml.match(/<!-- PRESERVED ([^>]*?) -->/)
if (preserved) {
  console.warn(`
⚠ Sitemap was PRESERVED from an earlier run, not regenerated by this build.`)
  console.warn(`   ${preserved[1].trim()}`)
  console.warn(`   The URLs are valid. Re-run the build once Supabase is reachable to refresh them.
`)
}

const locs = [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map(m => m[1])
if (locs.length < MIN_URLS) {
  fail(`only ${locs.length} <loc> entries (expected ≥ ${MIN_URLS}). Sitemap looks empty/broken.`)
}

// Freshness: the generator writes `Generated <iso>` into a comment.
const stamp = xml.match(/Generated (\d{4}-\d{2}-\d{2}T[\d:.]+Z)/)
if (!stamp) {
  fail('no "Generated <timestamp>" marker — cannot prove this sitemap was regenerated this build.')
}
const ageMin = (Date.now() - new Date(stamp[1]).getTime()) / 60_000
if (Number.isNaN(ageMin) || ageMin > MAX_AGE_MINUTES) {
  fail(`sitemap timestamp (${stamp[1]}) is ${Math.round(ageMin)} min old (> ${MAX_AGE_MINUTES}).
   It was NOT regenerated by this build — the generation step silently no-op'd.`)
}

// Origin + entity-escaping sanity.
const badOrigin = locs.filter(u => !u.startsWith(`${BASE_URL}/`) && u !== BASE_URL && u !== `${BASE_URL}/`)
if (badOrigin.length) {
  fail(`${badOrigin.length} <loc>(s) are not absolute URLs on ${BASE_URL}, e.g. ${badOrigin[0]}`)
}
if (/<loc>[^<]*&(?!amp;|lt;|gt;|quot;|apos;)/.test(xml)) {
  fail('a <loc> contains an unescaped & — the XML is not entity-safe.')
}

// Privacy/admin leak check.
const leaked = locs.filter(u => {
  const path = u.slice(BASE_URL.length)
  return isExcludedPath(path)
})
if (leaked.length) {
  fail(`${leaked.length} excluded/private path(s) leaked into the sitemap, e.g. ${leaked[0]}`)
}

console.log(`✅ Sitemap gate passed — ${locs.length} URLs, generated ${Math.round(ageMin)} min ago, no private paths.`)
